### ISSUE TITLE
Why is `koa-tree-router` picking `:param` as a wildcard?

### ISSUE THREAD

**Issue by ajimae** [steambap/koa-tree-router#27]
I have the following routes which works just fine.

```js
router.get('/note/:id', middlware);
router.get('/notes', middleware);
router.post('/note', middleware);
router.delete('/', middleware);
```

when I go another route instance and try registering another route as seen below I get an error.
```js
route2.get('/request-id', middleware);
```

The error:
```js
                    ^
error: wildcard route ':id' conflicts with existing children in path '/note/:id'
      at insertChild (/Users/username/**/lib/tree.ts:277:15)
      at addRoute (/Users/username/**/lib/tree.ts:229:9)
      at register (/Users/username/**/lib/router.ts:155:5)
      at all (/Users/username/**/lib/cols**.ts:175:9)
      at /Users/username/**/example/note-app/src/app.ts:64:1
272 |           "'"
273 |         );
274 |       }
272 |           "'"
273 |         );
274 |       }
275 | 
276 |       if (n.children.length > 0) {
277 |         throw new Error(
                    ^
```

Also, I notice if I change the order of this routes it throw the same error:

Changing this from
```js
router.get('/note/:id', middlware);
router.get('/notes', middleware);
router.post('/note', middleware);
router.delete('/', middleware);
```

To this:
```js
router.get('/notes', middleware);
router.get('/note/:id', middlware);
router.post('/note', middleware);
router.delete('/', middleware);
```

Doesn it have something to do with this [issue](https://github.com/steambap/koa-tree-router/issues/19)

**Comment by steambap** [comment]
There are some spelling error in your code example.... If I fix it, then there is no error after changing the router declaration order.

If you are seeing the wild card error, then it should be the same problem as the previous issue.
